[package]
name = "rust-ftp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libunftp = "0.18.1"
tokio = { version = "1", features = ["full"] }
unftp-sbe-fs = "0.2.0"
clap = "2.33.3"