name: Release Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf # Raspberry Pi
          - x86_64-pc-windows-gnu # Windows
          - x86_64-unknown-linux-gnu # Linux
          - x86_64-apple-darwin # Mac OS
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/rust-ftp